name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', if that's your branch

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy files to output folder
        run: |
          mkdir -p public
          cp -r * public/
          rm -rf public/.git public/.github

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
